[tool.poetry]
name = "docstring-builder"
version = "0.1.0"
description = ""
authors = ["Alistair Miles <alimanfoo@googlemail.com>"]
readme = "README.md"
packages = [{include = "docstring_builder"}]

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
