name: tests
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    tests:
        strategy:
            fail-fast: true
            matrix:
                python-version: ['3.10', '3.11', '3.12', '3.13']
                poetry-version: ['1.8.3']
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout source
              uses: actions/checkout@v3

            - name: Install poetry
              run: pipx install poetry==${{ matrix.poetry-version }}

            - name: Setup python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: 'poetry'

            - name: Install dependencies
              run: poetry install --with dev

            - name: Run tests
              run: poetry run pytest -v
